### ISSUE TITLE
Organization account

### ISSUE THREAD

**Issue by Namchee** [direbus/daily-watori#12]
Since this project is a collaboration between us (me and @chez14), would it be easier to transfer the ownership to an organization account? I think it's generally easier to manage since we can share ideas faster and you (@chez14) will have bigger control over this project.

**Comment by chez14** [comment]
Agree, what should we call our orgs? (will also update the Docker Orgs too to reflect this one).

Here's my suggestion:
- [Generation Bleu](https://eurekaseven.fandom.com/wiki/Generation_Bleu) (yes Bleu, spelt like that.)
- @direbus?
- Other? Let me know~!


Thanks!

**Comment by Namchee** [comment]
I prefer @direbus

**Comment by chez14** [comment]
@Namchee You can transfer it whenever you're ready :wink:

**Comment by Namchee** [comment]
Transferred, should take a little bit more time.
